# Generated by Django 4.2 on 2025-11-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
