# Generated by Django 4.2 on 2025-11-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.CharField(default='John', max_length=255),
        ),
    ]
