# Generated by Django 4.2 on 2025-11-22 08:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0003_purchaserequest_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='generated_pos/'),
        ),
    ]
