# Generated by Django 4.2 on 2025-11-23 08:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0004_alter_purchaseorder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvalidation',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='vendor',
            field=models.CharField(max_length=255),
        ),
    ]
