# Generated by Django 4.2 on 2025-11-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('approver_l1', 'Approver Level 1'), ('approver_l2', 'Approver Level 2'), ('finance', 'Finance'), ('admin', 'Admin')], default='staff', max_length=32),
        ),
    ]
